/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gest_bibliotheque;

import javax.swing.JOptionPane;

/**
 *
 * @author Cyrille
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        this.setResizable(false);
        this.setSize(600, 300);
        initComponents();
          this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_Rapport = new javax.swing.JButton();
        btn_Livres = new javax.swing.JButton();
        btn_Categorie = new javax.swing.JButton();
        btn_Quitter = new javax.swing.JButton();
        btn_Emprunt = new javax.swing.JButton();

        jButton4.setText("jButton1");

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton8.setText("Historique des Emprunts");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Système de Gestion d'une bilbliothèque");

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setText("SYSTEME DE GESTION D'UNE BIBLIOTHEQUE");

        btn_Rapport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Rapport.setText("Rapports");
        btn_Rapport.setActionCommand("Historique des Emprunts");
        btn_Rapport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Rapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RapportActionPerformed(evt);
            }
        });

        btn_Livres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Livres.setText("Gestion des livres");
        btn_Livres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Livres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LivresActionPerformed(evt);
            }
        });

        btn_Categorie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Categorie.setText("Gestion des Catégories");
        btn_Categorie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Categorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CategorieActionPerformed(evt);
            }
        });

        btn_Quitter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Quitter.setText("Quitter");
        btn_Quitter.setActionCommand("Historique des Emprunts");
        btn_Quitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Quitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuitterMouseClicked(evt);
            }
        });
        btn_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuitterActionPerformed(evt);
            }
        });

        btn_Emprunt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Emprunt.setText("Gestion des Emprunts");
        btn_Emprunt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Emprunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmpruntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btn_Livres, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btn_Emprunt)
                        .addGap(40, 40, 40)
                        .addComponent(btn_Categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btn_Rapport, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btn_Quitter)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Emprunt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Livres, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Rapport, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RapportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RapportActionPerformed

    private void btn_CategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CategorieActionPerformed
          Menu.super.dispose();
        gestion_categories categorie = new gestion_categories();
        categorie.setVisible(true);
    }//GEN-LAST:event_btn_CategorieActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btn_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuitterActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_QuitterActionPerformed

    private void btn_QuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuitterMouseClicked
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment quitter ?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_QuitterMouseClicked

    private void btn_LivresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LivresActionPerformed
        // TODO add your handling code here:
        Menu.super.dispose();
        gestion_livre livre = new gestion_livre();
        livre.setVisible(true);
    }//GEN-LAST:event_btn_LivresActionPerformed

    private void btn_EmpruntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpruntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EmpruntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Categorie;
    private javax.swing.JButton btn_Emprunt;
    private javax.swing.JButton btn_Livres;
    private javax.swing.JButton btn_Quitter;
    private javax.swing.JButton btn_Rapport;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
